-- Database schema for CSV Knowledge Base System
-- Execute these SQL commands in your Supabase SQL editor

-- Table for storing CSV documents
CREATE TABLE IF NOT EXISTS csv_documents (
    id SERIAL PRIMARY KEY,
    filename VARCHAR(255) NOT NULL,
    upload_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    file_size BIGINT,
    row_count INTEGER,
    column_count INTEGER,
    preview_data JSONB,
    full_data JSONB,
    is_described BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Table for storing document metadata (column information)
CREATE TABLE IF NOT EXISTS document_metadata (
    id SERIAL PRIMARY KEY,
    document_id INTEGER NOT NULL REFERENCES csv_documents(id) ON DELETE CASCADE,
    filename VARCHAR(255) NOT NULL,
    column_metadata JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(document_id)
);

-- Table for storing knowledge base entries (LLM analysis results)
CREATE TABLE IF NOT EXISTS knowledge_base (
    id SERIAL PRIMARY KEY,
    document_id INTEGER NOT NULL REFERENCES csv_documents(id) ON DELETE CASCADE,
    filename VARCHAR(255) NOT NULL,
    summary TEXT NOT NULL,
    data_category VARCHAR(100) NOT NULL,
    insights JSONB NOT NULL,
    use_cases JSONB NOT NULL,
    column_analysis JSONB NOT NULL,
    data_quality_score DECIMAL(5,2) NOT NULL DEFAULT 0.0,
    recommendations JSONB NOT NULL,
    column_metadata JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(document_id)
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_csv_documents_filename ON csv_documents(filename);
CREATE INDEX IF NOT EXISTS idx_csv_documents_upload_date ON csv_documents(upload_date DESC);
CREATE INDEX IF NOT EXISTS idx_csv_documents_is_described ON csv_documents(is_described);
CREATE INDEX IF NOT EXISTS idx_document_metadata_document_id ON document_metadata(document_id);
CREATE INDEX IF NOT EXISTS idx_knowledge_base_document_id ON knowledge_base(document_id);
CREATE INDEX IF NOT EXISTS idx_knowledge_base_filename ON knowledge_base(filename);
CREATE INDEX IF NOT EXISTS idx_knowledge_base_created_at ON knowledge_base(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_knowledge_base_data_category ON knowledge_base(data_category);
CREATE INDEX IF NOT EXISTS idx_knowledge_base_quality_score ON knowledge_base(data_quality_score DESC);

-- Create function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create triggers for automatic timestamp updates
CREATE TRIGGER update_csv_documents_updated_at 
    BEFORE UPDATE ON csv_documents 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_document_metadata_updated_at 
    BEFORE UPDATE ON document_metadata 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_knowledge_base_updated_at 
    BEFORE UPDATE ON knowledge_base 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Add comments for documentation
COMMENT ON TABLE document_metadata IS 'Stores user-provided metadata for CSV columns including connection keys, aliases, and descriptions';
COMMENT ON TABLE knowledge_base IS 'Stores LLM analysis results and processed knowledge base entries for CSV documents';

COMMENT ON COLUMN document_metadata.column_metadata IS 'JSON array containing column information with names, data types, connection keys, aliases, and descriptions';
COMMENT ON COLUMN knowledge_base.summary IS 'Brief summary of the dataset generated by LLM';
COMMENT ON COLUMN knowledge_base.data_category IS 'Primary category of the data (e.g., sales, customer, financial)';
COMMENT ON COLUMN knowledge_base.insights IS 'JSON array of key insights about the data';
COMMENT ON COLUMN knowledge_base.use_cases IS 'JSON array of potential use cases for the dataset';
COMMENT ON COLUMN knowledge_base.column_analysis IS 'JSON object containing detailed analysis of each column';
COMMENT ON COLUMN knowledge_base.data_quality_score IS 'Overall data quality score from 0-100';
COMMENT ON COLUMN knowledge_base.recommendations IS 'JSON array of recommendations for data usage';
COMMENT ON COLUMN knowledge_base.column_metadata IS 'JSON array containing the original column metadata used for LLM analysis';